### ISSUE TITLE
Parent Pub Key -> Child Pub Key

### ISSUE THREAD

**Issue by Andr3wHur5t** [Andr3wHur5t/Breadcrumb#2]
At the moment we are doing private parent -> private child -> child pub key this requires us to keep the memory key stored to retrieve addresses, we should be using parent public key -> child public key derivation instead.

https://github.com/Andr3wHur5t/Breadcrumb/blob/master/Breadcrumb/Breadcrumb/Keys/BCPublicKey.m#L65-L120

**Comment by rmhrisk** [comment]
divination = derivation
Date: Thu, 26 Feb 2015 14:11:47 -0800
