### ISSUE TITLE
Support for Pedersen commitments, borromean ring signatures, and ZK range proofs. 

### ISSUE THREAD

**Issue by Miyurz** [Andr3wHur5t/Breadcrumb#6]
Hi,

The project below supports Pedersen commitments, borromean ring signatures, and ZK range proofs but compiles for x86_64 only.

https://github.com/ElementsProject/secp256k1-zkp.git

Whereas Breadcrumb supports all architectures including armv7,armv7s and arm64 but doesn't include support for Pedersen commitments, borromean ring signatures, and ZK range proofs. It would be great help if Breadcrumb can support this.

Also there is no autogen.sh or configure file present in Breadcrumb. Appreciate if you can help with this.

secp256k1_ecdh.h
improve ECDH header-doc

secp256k1_rangeproof.h
Pedersen commitments, borromean ring signatures, and ZK range proofs.

secp256k1_recovery.h
Comment copyediting.

secp256k1_schnorr.h
Change secp256k1_ec_pubkey_combine's count argument to size_t.

**Comment by Andr3wHur5t** [comment]
This lib wouldn't take advantage of those features; but if you would like to build the `libsec256k1.a` you can use the `./makeiOS.sh` script in this project to generate a fat lib with all architectures iOS architectures. All you would need to then is link it. 

Note that there may be some assembly optimizations in the lib so it may not support these architectures, also there may be some present timing attacks present so I would check the output.
